---
- name: Ubuntu source
  include_tasks: "{{ Ubuntu_source }}/main.yml"
  when: Ubuntu_source != "default"

- name: Dependencies
  ansible.builtin.apt:
    pkg:
    - git
    - make
    - pandoc
    - zip
    # - nosetests
  become: true

- name: Ubuntu source
  include_tasks: git/main.yml