---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ git_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

- name: Git checkout
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ git_dir }}"
    # version: release-0.22

- name: Build the default target
  make:
    chdir: "{{ git_dir }}"

- name: Run 'install' target as root
  make:
    chdir: "{{ git_dir }}"
    target: install
  become: yes